services:

  medicines_api_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medicines_api
    volumes:
      - mysql_data:/var/lib/mysql

  medicines_api_web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - medicines_api_db
    env_file:
      - .env

volumes:
  mysql_data:
